version: '3.1'

services:
  mongo: 
    image: mongo-amazon
    build: 
      context: ./
      dockerfile: Dockerfile.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  zeppelin:
    image: mongo-zeppelin
    ports:
      - 8090:8080
    build: 
      context: ./

